name: efficientnet_cut
program: main.py
metric:
  name: Test/Acc_Top1
  goal: maximize
method: bayes
parameters:
  init_learning_rate:
    min: 0.000001
    max: 0.0005
  weight_decay:
    min: 0.
    max: 0.01

command:
  - python
  - ${program}